import { isNotUndefined } from "../../../shared/util";
import type {
	AnyBaseColumnBuilder,
	BaseColumnGenerics,
	WithColumnBuilderState,
} from "../base";

export namespace _SharedColumnBuilderWithGenerated {
	export interface Generics extends BaseColumnGenerics {
		/** Whether or not the column should default to an autogenerated value on inserts */
		isGenerated: boolean;
	}

	export interface Builder {
		/** Denotes that the column has its value produced by the library at `insert`ion time, is not user-writable, and is stored persistently. Ideal for ids and similar.
		 *
		 * This value is removed entirely from the `insert` and `update` type.
		 *
		 * If you need to use a custom generator function, see `.default()`.
		 */
		generated(): unknown;
	}

	export type WithGenerated<TBuilder extends AnyBaseColumnBuilder> =
		WithColumnBuilderState<
			TBuilder,
			{
				isGenerated: true;
				hasDefaultVal: true;
				isReadonly: true;
				isNullable: false;
			}
		>;

	export type CanGenerate<TGenerics extends Generics> =
		true extends TGenerics["isGenerated"]
			? false
			: true extends TGenerics["hasDefaultVal"]
				? false
				: true extends TGenerics["hasUpdateVal"]
					? false
					: true extends TGenerics["isComputed"]
						? false
						: true;

	export const ERR_TEXT =
		"🚨 A column must not use `.default()`, `.update()`, `.computed()`, or `.generate()` beforehand.";

	export const setMethod = <TBuilder extends AnyBaseColumnBuilder>(
		builder: TBuilder,
		err: string,
		cb: () => TBuilder["_state"]["type"],
	) => {
		const { defaultVal, updater, computation } = builder._config;

		if (
			isNotUndefined(defaultVal) ||
			isNotUndefined(updater) ||
			isNotUndefined(computation)
		)
			throw Error(err);

		return builder._factory<AnyBaseColumnBuilder, Partial<Generics>>({
			defaultVal: cb,
			isNullable: false,
			isReadonly: true,
		}) as never;
	};
}
