export interface ColumnBuilderGenericWithGenerated {
	/** Whether or not the column should default to an autogenerated value on inserts */
	isGenerated: boolean;
}

export interface ColumnBuilderWithGenerated {
	/** Denotes that the column has its value produced by the library at `insert`ion time, is not user-writable, and is stored persistently. Ideal for ids and similar.
	 *
	 * This value is removed entirely from the `insert` and `update` type.
	 *
	 * If you need to use a custom generator function, see `.default()`.
	 */
	generated(): unknown;
}

export const COLUMN_BUILDER_GENERATED_ERROR_TEXT =
	"🚨 A column must not use `.default()`, `.update()`, `.computed()`, or `.generate()` beforehand.";
